name: teszt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nima: ^1.0.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  

  
  assets:
  - Big Green Guy.nma
  - Big Green Guy0.png
  - Big Green Guy1.png
  - Big Green Guy2.png
  - Big Green Guy3.png
  - Big Green Guy4.png
  - Big Green Guy5.png

  